Update airports
nerds-and-company/airports pull request #1
Opened 2022-01-06 04:48 UTC by samhamilton

Hi, 

We have updated a few things so please let me know if there are any problems

- rather than use openflights.org, we went to their upstream source of https://davidmegginson.github.io/ourairports-data/
- added basic github tests
- mix format

Thanks
Sam

2022-01-25 03:01 UTC, samhamilton commented
Hey @sjoulbak - was not clear who I should ping in your org to help with this PR?

2022-01-25 07:15 UTC, sjoulbak commented
Hi @samhamilton! 🎉 

Thank you and @christianlj for your contribution! I will be looking into this more closely tomorrow afternoon.

One thing that I noticed is that the airport struct attributes have been changed with this PR. This will cause upgrade issues for other users of this dependency. Why do you want to change the upstream source?

2022-01-25 07:29 UTC, samhamilton commented
thanks @sjoulbak. 

We decided to change the data source as the one currently used has not been [updated since 2019](https://github.com/jpatokal/openflights/commits/master/data/airports.dat) where as the new source (which is listed on the openflights website) is [updated daily(!)](https://github.com/davidmegginson/ourairports-data/commits/main/airports.csv) 

Very happy to adjust source data if you know of a better place to pull it from?

We could add a changelog and also make the version bump indicative that something major happened for anyone updating the hex package?

2022-02-03 06:26 UTC, sjoulbak commented
Hi @samhamilton,

I'm sorry it took some more time than expected. Thank you for providing the information about the airports data, it makes now sense. 

I've been thinking about the changelog idea and I agree that we should add it with a major bump, so everyone can see that some major changes will happen. Could you provide that aswel? I'll try to pick it up if I get to it sooner.

2022-02-05 05:33 UTC, samhamilton commented
@sjoulbak just updated the pull - added changelog and also bumped the version.

2022-02-16 11:07 UTC, samhamilton commented
hey @sjoulbak just wanted to check if you would like any more changes?

2022-02-16 17:35 UTC, sjoulbak commented
Hi @samhamilton,

Yes, just one more change and then it is fine. Since it is a big rewrite of the code base, I would like to see a version bump to 1.0.0. Could you do that for me?

And, if it possible, update the csv for once more? 😇

2022-02-17 03:01 UTC, samhamilton commented
@sjoulbak sure thing - pushed updates

2022-02-17 11:17 UTC, sjoulbak requested changes

2022-02-17 11:17 UTC, sjoulbak commented on .github/workflows/elixir.yml
> +  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
Since we're not using `coveralls.post`, this variable is unnecessary. Can you remove it?

2022-02-17 11:17 UTC, sjoulbak commented on .tool-versions
> +nodejs 16.13.0
Nice that you're using `asdf`! I don't think that this nodejs version is not necessary for this project

2022-02-17 11:17 UTC, sjoulbak commented on README.md
> +  [{:airports, "~> 0.2.0"}]
```suggestion
  [{:airports, "~> 1.0.0"}]
```

2022-02-17 11:17 UTC, sjoulbak commented on mix.exs
> +      version: "0.2.0",
```suggestion
      version: "1.0.0",
```

2022-02-19 04:16 UTC, samhamilton commented on .github/workflows/elixir.yml
> +  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
sure - removed

2022-02-19 04:16 UTC, samhamilton commented on .tool-versions
> +nodejs 16.13.0
sure - removed

2022-02-19 04:16 UTC, samhamilton commented on README.md
> +  [{:airports, "~> 0.2.0"}]
Bumped, removed the minor version for less readme updates

2022-02-19 04:17 UTC, samhamilton commented on mix.exs
> +      version: "0.2.0",
bumped

2022-02-19 04:17 UTC, samhamilton commented
@sjoulbak sorry about that - all updated

2022-02-21 06:21 UTC, sjoulbak approved these changes

2022-02-21 06:22 UTC, sjoulbak commented
No problem @samhamilton! Thank you and @christianlj for your contribution!

2022-02-21 06:22 UTC, merged

2022-02-21 06:51 UTC, samhamilton commented
Thanks @sjoulbak - when you get a min would you mind publishing the package to hex?

2024-07-18 13:08 UTC, sjoulbak commented
@samhamilton Excuse me about not reacting anymore. I noticed you opening #21. Are you still making use of this package?

2024-07-18 13:15 UTC, samhamilton commented
@sjoulbak yes though we are having to use our fork right now as we updated the airport database. We can open a new PR if you plan to cut a hex release?

2024-07-18 13:16 UTC, sjoulbak commented
@samhamilton Yes that would be nice!